### ISSUE TITLE
Handle ToS when key is already registered

### ISSUE THREAD

**Issue by reynir** [mmaker/ocaml-letsencrypt#14]
When a key has been registered without accepting the terms-of-service, the `terms-of-service` link is missing from the headers when calling new-reg. Furthermore, it's seemingly not possible to tell the difference between registered-and-accepted and registered-not-accepted from the response code. When calling new-reg, there *is* a `Location` header containing a link to a `reg` resource. Perhaps the way to accept is query this `Location` to get `terms-of-service` and then follow the new `Location` link, or redo the request if no `Location` header is present, with the `agreement` field.

**Comment by reynir** [comment]
This should make it much easier to implement https://github.com/letsencrypt/boulder/pull/2745

**Comment by hannesm** [comment]
while this is completely different now, the actual case (key registered without agreeing to the ToS) seems to be not supported by the LE servers anymore.

but as a drawback, what still is not implemented (see the TODO comment in letsencypt.mli) is if LE decides to change their ToS, in which case somewhere a 403 is sent back which should be handled appropriately. I'll nevertheless close this issue for now, if you feel motivated, please look how to improve the current code (now, errors are reported in a typed way, so it should be doable -- I just don't see the use of handling it right now -- imho there are other missing pieces that are more important to be implemented) :)
